import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
import 'tailwindcss'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav >
          <ul className='flex items-center flex-wrap bg-gray-950 divide-opacity-95 p-6'>
            <li className='mr-6'>
              <Link href={'/'} className='text-blue-500 hover:text-blue-800'>Home</Link>
            </li>
            <li className='mr-6'>
              <Link href={'/pokedex'} className='text-blue-500 hover:text-blue-800'>Pokedex</Link>
            </li>
            <li className='mr-6 absolute right-1'>
              <Link href={'/login'} className='text-blue-500 hover:text-blue-800'>Login</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
